// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"database/sql"
)

type Task struct {
	ID          int64
	Title       string
	Notes       sql.NullString
	Done        int64
	CreatedAt   int64
	CompletedAt sql.NullInt64
}
