// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package model

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
insert into task (title, notes, created_at)
values (?, ?, ?)
returning id, title, notes, done, created_at, completed_at
`

type CreateTaskParams struct {
	Title     string
	Notes     sql.NullString
	CreatedAt int64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Title, arg.Notes, arg.CreatedAt)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Done,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
delete from task
where id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTask = `-- name: GetTask :one
select id, title, notes, done, created_at, completed_at
from task
where id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Done,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
select id, title, notes, done, created_at, completed_at
from task
order by id
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Done,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByDone = `-- name: ListTasksByDone :many
select id, title, notes, done, created_at, completed_at
from task
where done = ?
order by id
`

func (q *Queries) ListTasksByDone(ctx context.Context, done int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByDone, done)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.Done,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
update task
set
    title = ?,
    notes = ?,
    done = ?,
    completed_at = ?
where id = ?
returning id, title, notes, done, created_at, completed_at
`

type UpdateTaskParams struct {
	Title       string
	Notes       sql.NullString
	Done        int64
	CompletedAt sql.NullInt64
	ID          int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Notes,
		arg.Done,
		arg.CompletedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Done,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
