// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package model

import (
	"context"
)

const getTenant = `-- name: GetTenant :one
select id, master_id, slug, name, synced_at
from tenant
where id = 1
`

func (q *Queries) GetTenant(ctx context.Context) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Slug,
		&i.Name,
		&i.SyncedAt,
	)
	return i, err
}

const upsertTenant = `-- name: UpsertTenant :exec
insert into tenant (id, master_id, slug, name, synced_at)
values (1, ?, ?, ?, ?)
on conflict (id) do update
set
    master_id = excluded.master_id,
    slug = excluded.slug,
    name = excluded.name,
    synced_at = excluded.synced_at
`

type UpsertTenantParams struct {
	MasterID int64
	Slug     string
	Name     string
	SyncedAt int64
}

func (q *Queries) UpsertTenant(ctx context.Context, arg UpsertTenantParams) error {
	_, err := q.db.ExecContext(ctx, upsertTenant,
		arg.MasterID,
		arg.Slug,
		arg.Name,
		arg.SyncedAt,
	)
	return err
}
