// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company.sql

package model

import (
	"context"
)

const createCompany = `-- name: CreateCompany :one
insert into company (slug, name, created_at)
values (?, ?, ?)
returning id, slug, name, created_at
`

type CreateCompanyParams struct {
	Slug      string
	Name      string
	CreatedAt int64
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, arg.Slug, arg.Name, arg.CreatedAt)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :one
delete from company
where slug = ?
returning id, slug, name, created_at
`

func (q *Queries) DeleteCompany(ctx context.Context, slug string) (Company, error) {
	row := q.db.QueryRowContext(ctx, deleteCompany, slug)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
select id, slug, name, created_at
from company
where id = ?
`

func (q *Queries) GetCompany(ctx context.Context, id int64) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getCompanyBySlug = `-- name: GetCompanyBySlug :one
select id, slug, name, created_at
from company
where slug = ?
`

func (q *Queries) GetCompanyBySlug(ctx context.Context, slug string) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyBySlug, slug)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
select id, slug, name, created_at
from company
order by slug
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyIDs = `-- name: ListCompanyIDs :many
select id
from company
order by id
`

func (q *Queries) ListCompanyIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCompanyIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
update company
set name = ?
where slug = ?
returning id, slug, name, created_at
`

type UpdateCompanyParams struct {
	Name string
	Slug string
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompany, arg.Name, arg.Slug)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
