// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company.sql

package model

import (
	"context"
)

const getCompany = `-- name: GetCompany :one
select id, master_id, slug, name, synced_at
from company
where id = 1
`

func (q *Queries) GetCompany(ctx context.Context) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.MasterID,
		&i.Slug,
		&i.Name,
		&i.SyncedAt,
	)
	return i, err
}

const upsertCompany = `-- name: UpsertCompany :exec
insert into company (id, master_id, slug, name, synced_at)
values (1, ?, ?, ?, ?)
on conflict (id) do update
set
    master_id = excluded.master_id,
    slug = excluded.slug,
    name = excluded.name,
    synced_at = excluded.synced_at
`

type UpsertCompanyParams struct {
	MasterID int64
	Slug     string
	Name     string
	SyncedAt int64
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompany,
		arg.MasterID,
		arg.Slug,
		arg.Name,
		arg.SyncedAt,
	)
	return err
}
